import { useState, useEffect } from 'react';
import ToolLayout from '../../layout/ToolLayout';
import toolsData from '../../../data/tools.json';
import { useToast } from '../../common/Toast';
import useDraft from '../../../hooks/useDraft';

const AllInOneMetaGenerator = () => {
    const toast = useToast();

    // Use draft hook for persistent form state
    const [formData, setFormData, clearDraft, hasDraft] = useDraft('all-in-one-meta-generator', {
        pageType: 'website',
        title: '',
        description: '',
        keywords: '',
        url: '',
        siteName: '',
        ogImage: '',
        twitterHandle: '',
        includeBasic: true,
        includeOG: true,
        includeTwitter: true,
        includeCanonical: true,
        includeRobots: true,
        robotsIndex: true,
        robotsFollow: true
    });

    // Destructure for easier access
    const { pageType, title, description, keywords, url, siteName, ogImage, twitterHandle,
        includeBasic, includeOG, includeTwitter, includeCanonical, includeRobots, robotsIndex, robotsFollow } = formData;

    // Update helper
    const updateField = (field, value) => setFormData(prev => ({ ...prev, [field]: value }));

    const relatedTools = toolsData.tools.filter(t => t.category === 'seo' && t.id !== 'all-in-one-meta-generator').slice(0, 3);

    // Generate all meta tags
    const generateCode = () => {
        const lines = [];
        lines.push('<!-- Meta Tags Generated by NeoFreeTools -->');
        lines.push('');

        // Basic meta tags
        if (includeBasic) {
            lines.push('<!-- Basic Meta Tags -->');
            if (title) lines.push(`<title>${title}</title>`);
            if (description) lines.push(`<meta name="description" content="${description}" />`);
            if (keywords) lines.push(`<meta name="keywords" content="${keywords}" />`);
            lines.push('<meta name="viewport" content="width=device-width, initial-scale=1.0" />');
            lines.push('<meta charset="UTF-8" />');
            lines.push('');
        }

        // Robots
        if (includeRobots) {
            const robotsContent = `${robotsIndex ? 'index' : 'noindex'}, ${robotsFollow ? 'follow' : 'nofollow'}`;
            lines.push('<!-- Robots -->');
            lines.push(`<meta name="robots" content="${robotsContent}" />`);
            lines.push('');
        }

        // Canonical
        if (includeCanonical && url) {
            lines.push('<!-- Canonical -->');
            lines.push(`<link rel="canonical" href="${url}" />`);
            lines.push('');
        }

        // Open Graph
        if (includeOG) {
            lines.push('<!-- Open Graph / Facebook -->');
            lines.push(`<meta property="og:type" content="${pageType}" />`);
            if (title) lines.push(`<meta property="og:title" content="${title}" />`);
            if (description) lines.push(`<meta property="og:description" content="${description}" />`);
            if (url) lines.push(`<meta property="og:url" content="${url}" />`);
            if (siteName) lines.push(`<meta property="og:site_name" content="${siteName}" />`);
            if (ogImage) lines.push(`<meta property="og:image" content="${ogImage}" />`);
            lines.push('');
        }

        // Twitter Card
        if (includeTwitter) {
            lines.push('<!-- Twitter Card -->');
            lines.push('<meta name="twitter:card" content="summary_large_image" />');
            if (title) lines.push(`<meta name="twitter:title" content="${title}" />`);
            if (description) lines.push(`<meta name="twitter:description" content="${description}" />`);
            if (ogImage) lines.push(`<meta name="twitter:image" content="${ogImage}" />`);
            if (twitterHandle) lines.push(`<meta name="twitter:site" content="@${twitterHandle.replace('@', '')}" />`);
            lines.push('');
        }

        return lines.join('\n').trim();
    };

    const copyCode = () => {
        const code = generateCode();
        if (!code || code === '<!-- Meta Tags Generated by NeoFreeTools -->') {
            toast.warning('Please fill in at least title or description');
            return;
        }
        navigator.clipboard.writeText(code);
        toast.success('All meta tags copied!');
    };

    const download = () => {
        const code = generateCode();
        const blob = new Blob([code], { type: 'text/html' });
        const a = document.createElement('a');
        a.href = URL.createObjectURL(blob);
        a.download = 'meta-tags.html';
        a.click();
    };

    // Count tags
    const countTags = () => {
        let count = 0;
        if (includeBasic) count += 3 + (title ? 1 : 0) + (description ? 1 : 0) + (keywords ? 1 : 0);
        if (includeRobots) count += 1;
        if (includeCanonical && url) count += 1;
        if (includeOG) count += 2 + (title ? 1 : 0) + (description ? 1 : 0) + (url ? 1 : 0) + (siteName ? 1 : 0) + (ogImage ? 1 : 0);
        if (includeTwitter) count += 1 + (title ? 1 : 0) + (description ? 1 : 0) + (ogImage ? 1 : 0) + (twitterHandle ? 1 : 0);
        return count;
    };

    const faqs = [
        { question: 'What meta tags are essential?', answer: 'Title, description, viewport, and charset are essential. Canonical helps with duplicate content. OG and Twitter cards improve social sharing.' },
        { question: 'Where do I place meta tags?', answer: 'All meta tags go inside the <head> section of your HTML, typically after the opening <head> tag and before any stylesheets or scripts.' },
        { question: 'What size should OG images be?', answer: 'Recommended: 1200x630 pixels for optimal display on Facebook and most platforms. Twitter prefers 1200x628. Use high-quality images under 5MB.' }
    ];

    const seoContent = (<><h2>All-in-One Meta Generator</h2><p>Generate all essential meta tags in one place—basic meta, Open Graph, Twitter Cards, canonical, and robots tags.</p></>);

    return (
        <ToolLayout title="All-in-One Meta Tag Generator" description="Generate all essential meta tags at once. Basic meta, OG, Twitter, canonical, and robots tags combined." keywords={['meta tag generator', 'all meta tags', 'OG generator', 'SEO meta']} category="seo" categoryName="SEO & Webmaster" faqs={faqs} relatedTools={relatedTools} seoContent={seoContent}>
            <div className="tool-form">
                <div className="form-grid">
                    {/* Left: Inputs */}
                    <div className="inputs-section">
                        <div className="section-header">
                            <h4>📝 Page Information</h4>
                            {hasDraft && <button className="btn-clear-draft" onClick={() => { clearDraft(); toast.success('Draft cleared'); }}>🗑️ Clear Draft</button>}
                        </div>

                        <div className="form-group">
                            <label>Page Type</label>
                            <select value={pageType} onChange={(e) => updateField('pageType', e.target.value)}>
                                <option value="website">Website</option>
                                <option value="article">Article</option>
                                <option value="product">Product</option>
                                <option value="profile">Profile</option>
                                <option value="video">Video</option>
                            </select>
                        </div>

                        <div className="form-group">
                            <label>Page Title <span className="char-hint">{title.length}/60</span></label>
                            <input type="text" value={title} onChange={(e) => updateField('title', e.target.value)} placeholder="Your Page Title | Brand" maxLength={70} />
                        </div>

                        <div className="form-group">
                            <label>Meta Description <span className="char-hint">{description.length}/160</span></label>
                            <textarea value={description} onChange={(e) => updateField('description', e.target.value)} placeholder="A compelling description of your page..." rows={3} maxLength={200} />
                        </div>

                        <div className="form-group">
                            <label>Keywords (comma-separated)</label>
                            <input type="text" value={keywords} onChange={(e) => updateField('keywords', e.target.value)} placeholder="keyword1, keyword2, keyword3" />
                        </div>

                        <div className="form-row">
                            <div className="form-group">
                                <label>Page URL (Canonical)</label>
                                <input type="url" value={url} onChange={(e) => updateField('url', e.target.value)} placeholder="https://example.com/page" />
                            </div>
                            <div className="form-group">
                                <label>Site Name</label>
                                <input type="text" value={siteName} onChange={(e) => updateField('siteName', e.target.value)} placeholder="Your Brand" />
                            </div>
                        </div>

                        <div className="form-row">
                            <div className="form-group">
                                <label>OG Image URL</label>
                                <input type="url" value={ogImage} onChange={(e) => updateField('ogImage', e.target.value)} placeholder="https://example.com/image.jpg" />
                            </div>
                            <div className="form-group">
                                <label>Twitter Handle</label>
                                <input type="text" value={twitterHandle} onChange={(e) => updateField('twitterHandle', e.target.value)} placeholder="@yourhandle" />
                            </div>
                        </div>

                        {/* Options */}
                        <div className="options-section">
                            <h4>⚙️ Include Tags</h4>
                            <div className="options-grid">
                                <label className="checkbox"><input type="checkbox" checked={includeBasic} onChange={(e) => updateField('includeBasic', e.target.checked)} /> Basic Meta</label>
                                <label className="checkbox"><input type="checkbox" checked={includeOG} onChange={(e) => updateField('includeOG', e.target.checked)} /> Open Graph</label>
                                <label className="checkbox"><input type="checkbox" checked={includeTwitter} onChange={(e) => updateField('includeTwitter', e.target.checked)} /> Twitter Card</label>
                                <label className="checkbox"><input type="checkbox" checked={includeCanonical} onChange={(e) => updateField('includeCanonical', e.target.checked)} /> Canonical</label>
                                <label className="checkbox"><input type="checkbox" checked={includeRobots} onChange={(e) => updateField('includeRobots', e.target.checked)} /> Robots</label>
                            </div>

                            {includeRobots && (
                                <div className="robots-options">
                                    <label className="checkbox"><input type="checkbox" checked={robotsIndex} onChange={(e) => updateField('robotsIndex', e.target.checked)} /> Index</label>
                                    <label className="checkbox"><input type="checkbox" checked={robotsFollow} onChange={(e) => updateField('robotsFollow', e.target.checked)} /> Follow</label>
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Right: Output */}
                    <div className="output-section">
                        <div className="output-header">
                            <h4>📋 Generated Tags ({countTags()})</h4>
                            <div className="btn-group">
                                <button className="btn-secondary" onClick={copyCode}>📋 Copy All</button>
                                <button className="btn-secondary" onClick={download}>⬇️ Download</button>
                            </div>
                        </div>
                        <div className="code-output">
                            <pre>{generateCode()}</pre>
                        </div>
                    </div>
                </div>
            </div>
            <style>{`
                .tool-form{max-width:1100px;margin:0 auto}
                .form-grid{display:grid;grid-template-columns:1fr 1fr;gap:var(--spacing-lg)}
                .inputs-section{background:var(--bg-secondary);padding:var(--spacing-lg);border-radius:var(--radius)}
                .section-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:var(--spacing-md)}
                .section-header h4{margin:0}
                .btn-clear-draft{background:transparent;color:#dc3545;border:1px solid #dc3545;padding:4px 10px;border-radius:var(--radius);cursor:pointer;font-size:var(--text-xs)}
                .btn-clear-draft:hover{background:#dc3545;color:white}
                .form-group{margin-bottom:var(--spacing-md)}
                .form-group label{display:flex;justify-content:space-between;margin-bottom:var(--spacing-xs);font-weight:500;font-size:var(--text-sm)}
                .char-hint{font-weight:normal;color:var(--text-muted)}
                .form-group input,.form-group select,.form-group textarea{width:100%;padding:8px 12px;border:1px solid var(--platinum);border-radius:var(--radius)}
                .form-row{display:grid;grid-template-columns:1fr 1fr;gap:var(--spacing-md)}
                .options-section{margin-top:var(--spacing-lg);padding-top:var(--spacing-md);border-top:1px solid var(--platinum)}
                .options-section h4{margin:0 0 var(--spacing-sm) 0}
                .options-grid{display:flex;flex-wrap:wrap;gap:var(--spacing-md)}
                .checkbox{display:flex;align-items:center;gap:var(--spacing-xs);cursor:pointer}
                .robots-options{display:flex;gap:var(--spacing-md);margin-top:var(--spacing-sm);padding-left:var(--spacing-md)}
                .output-section{display:flex;flex-direction:column}
                .output-header{display:flex;justify-content:space-between;align-items:center;margin-bottom:var(--spacing-md)}
                .output-header h4{margin:0}
                .btn-group{display:flex;gap:var(--spacing-xs)}
                .btn-secondary{background:var(--yinmn-blue);color:white;border:none;padding:var(--spacing-xs) var(--spacing-sm);border-radius:var(--radius);cursor:pointer;font-size:var(--text-sm)}
                .code-output{flex:1;background:var(--bg-dark);color:#f0f0f0;padding:var(--spacing-lg);border-radius:var(--radius);overflow:auto}
                .code-output pre{font-family:var(--font-mono);font-size:12px;white-space:pre-wrap;margin:0;line-height:1.5}
                @media(max-width:900px){.form-grid{grid-template-columns:1fr}.form-row{grid-template-columns:1fr}}
            `}</style>
        </ToolLayout>
    );
};

export default AllInOneMetaGenerator;
