import { useState } from 'react';
import ToolLayout from '../../layout/ToolLayout';
import toolsData from '../../../data/tools.json';
import { useToast } from '../../common/Toast';

const HtaccessGenerator = () => {
    const toast = useToast();
    const [options, setOptions] = useState({ www: 'force-www', https: true, gzip: true, caching: true, hotlink: false, domain: '' });
    const relatedTools = toolsData.tools.filter(t => t.category === 'seo' && t.id !== 'htaccess-generator').slice(0, 3);

    const generateCode = () => {
        let code = '# Generated by NeoWebTools\n\n';
        if (options.https) code += '# Force HTTPS\nRewriteEngine On\nRewriteCond %{HTTPS} off\nRewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]\n\n';
        if (options.www === 'force-www') code += '# Force WWW\nRewriteCond %{HTTP_HOST} !^www\\. [NC]\nRewriteRule ^(.*)$ https://www.%{HTTP_HOST}/$1 [R=301,L]\n\n';
        else if (options.www === 'remove-www') code += '# Remove WWW\nRewriteCond %{HTTP_HOST} ^www\\.(.*)$ [NC]\nRewriteRule ^(.*)$ https://%1/$1 [R=301,L]\n\n';
        if (options.gzip) code += '# Enable GZIP Compression\n<IfModule mod_deflate.c>\nAddOutputFilterByType DEFLATE text/html text/plain text/css application/javascript\n</IfModule>\n\n';
        if (options.caching) code += '# Browser Caching\n<IfModule mod_expires.c>\nExpiresActive On\nExpiresByType image/jpg "access 1 year"\nExpiresByType image/png "access 1 year"\nExpiresByType text/css "access 1 month"\nExpiresByType application/javascript "access 1 month"\n</IfModule>\n\n';
        if (options.hotlink && options.domain) code += `# Hotlink Protection\nRewriteCond %{HTTP_REFERER} !^$\nRewriteCond %{HTTP_REFERER} !^https?://(www\\.)?${options.domain.replace('.', '\\.')}/ [NC]\nRewriteRule \\.(jpg|jpeg|png|gif)$ - [F,NC,L]\n\n`;
        return code;
    };

    const copyCode = () => { navigator.clipboard.writeText(generateCode()); toast.success('Copied to clipboard!'); };

    const faqs = [
        { question: 'What is .htaccess?', answer: '.htaccess is an Apache server configuration file that controls URL rewriting, redirects, security, and performance settings for your website.' },
        { question: 'Where to place .htaccess?', answer: 'Place .htaccess in your website root directory. It affects that directory and all subdirectories. Only works on Apache servers, not Nginx.' }
    ];

    const seoContent = (<><h2>.htaccess Generator</h2><p>Generate .htaccess rules for Apache web servers. Configure redirects, HTTPS forcing, compression, and caching easily.</p></>);

    return (
        <ToolLayout title=".htaccess Generator" description="Generate Apache .htaccess file for redirects, HTTPS, caching, and compression." keywords={['htaccess generator', 'Apache htaccess', 'redirect rules', 'server config']} category="seo" categoryName="SEO & Webmaster" faqs={faqs} relatedTools={relatedTools} seoContent={seoContent}>
            <div className="tool-form">
                <div className="options-grid">
                    <label><input type="checkbox" checked={options.https} onChange={(e) => setOptions({ ...options, https: e.target.checked })} /> Force HTTPS</label>
                    <label><input type="checkbox" checked={options.gzip} onChange={(e) => setOptions({ ...options, gzip: e.target.checked })} /> Enable GZIP</label>
                    <label><input type="checkbox" checked={options.caching} onChange={(e) => setOptions({ ...options, caching: e.target.checked })} /> Browser Caching</label>
                    <label><input type="checkbox" checked={options.hotlink} onChange={(e) => setOptions({ ...options, hotlink: e.target.checked })} /> Hotlink Protection</label>
                </div>
                <div className="form-row">
                    <div className="form-group"><label className="form-label">WWW Preference</label><select className="form-select" value={options.www} onChange={(e) => setOptions({ ...options, www: e.target.value })}><option value="none">No Change</option><option value="force-www">Force WWW</option><option value="remove-www">Remove WWW</option></select></div>
                    <div className="form-group"><label className="form-label">Your Domain (for hotlink)</label><input type="text" className="form-input" value={options.domain} onChange={(e) => setOptions({ ...options, domain: e.target.value })} placeholder="example.com" /></div>
                </div>
                <div className="code-output"><pre>{generateCode()}</pre><button className="copy-btn" onClick={copyCode}>📋 Copy</button></div>
            </div>
            <style>{`.tool-form{max-width:700px;margin:0 auto}.options-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:var(--spacing-md);margin-bottom:var(--spacing-lg)}.options-grid label{display:flex;align-items:center;gap:var(--spacing-sm);cursor:pointer;padding:var(--spacing-sm);background:var(--bg-secondary);border-radius:var(--radius)}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:var(--spacing-md)}.form-input{width:100%;padding:var(--spacing-sm);border:2px solid var(--platinum);border-radius:var(--radius)}.code-output{background:var(--bg-dark);color:#f0f0f0;padding:var(--spacing-lg);border-radius:var(--radius);position:relative;margin-top:var(--spacing-lg)}.code-output pre{font-family:var(--font-mono);font-size:var(--text-sm);white-space:pre-wrap;margin:0}.copy-btn{position:absolute;top:var(--spacing-sm);right:var(--spacing-sm);background:var(--yinmn-blue);color:white;border:none;padding:var(--spacing-xs) var(--spacing-sm);border-radius:var(--radius);cursor:pointer}`}</style>
        </ToolLayout>
    );
};

export default HtaccessGenerator;
